Information on data in python that may be useful: 
Users of Python are often drawn-in by its ease of use, one piece of which is dynamic typing. While a statically-typed language like C or Java requires each variable to be explicitly declared, a dynamically-typed language like Python skips this specification. 

The standard Python implementation is written in C. This means that every Python object is simply a cleverly-disguised C structure, which contains not only its value, but other information as well.

Because of Python's dynamic typing, we can even create heterogeneous lists, but this flexibility comes at a cost: to allow these flexible types, each item in the list must contain its own type info, reference count, and other information–that is, each item is a complete Python object. 

In [28]:
import numpy as np 

#integer array
np.array([1,4,2,5,3])

#set data type of array
np.array([1,2,3,4,5], dtype='float32')

#Unlike python lists, NumPy arrays can be mulit-dimensional
#Initialize mulit-dimensional array - in the list [2,5,6] each number in that list is the start of 
np.array([range(i, i+3) for i in [2,5,6]])


array([[2, 3, 4],
       [5, 6, 7],
       [6, 7, 8]])

In [29]:
#More efficient to create arrays from scratch using NumPy functions

#create 3x5 floating-point array filled with ones
np.ones((3,5), dtype=float)

#create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

#create 3x5 array filled with 3.14
np.full((3,5), 3.14)

# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[9, 9, 8],
       [9, 3, 9],
       [1, 5, 9]])

Array Attributes
Attributes of arrays: Determining the size, shape, memory consumption, and data types of arrays
Indexing of arrays: Getting and setting the value of individual array elements
Slicing of arrays: Getting and setting smaller subarrays within a larger array
Reshaping of arrays: Changing the shape of a given array
Joining and splitting of arrays: Combining multiple arrays into one, and splitting one array into many

In [32]:
#Define three random arrays: one-dimensional, two-dimensional, three-dimemnsional

import numpy as np 

np.random.seed

x1 = np.random.randint(10) #1D
x2 = np.random.randint(0, 10, (3, 4)) #2D
x3 = np.random.randint(0, 10, (3, 4, 5)) #3D

#each array has attributes
x2.shape #size of each dimension
x2.ndim #number of dimensions 
x2.size #total size of array 

#itemsize lists the size (in bytes) of each array element, and nbytes which lists the total size (in bytes) of the array 
#array indexing: array[i] = array([i0, i1, i2,...])
#negative indexing can be used to index from the end of the array
x1[-2]

#array slicing: 
#x[start:stop:step], default to the alues start=0, stop=size oof dimension, step=1
x1[:3] #first three elements
x1[3:] #elements after index 3
x1[1:4] #middle subarray
x1[::2] #every second element
x1[1::2] #every second element, starting at index 1
x1[::-1] #all elements, reversed
x1[4::-2] #every second element from index 4, reversed

#multidimensional subarrays
x2[:2, :3] #first two rows & three columns
x2[:3, ::2] #three rows, every second column
x2[::-1, ::-1] #all rows and columns, reversed 

#accessing single rows or columns of an array via combining indexing and slicing 
x2[:, 0] #first column of x2
x2[, 0] #DOES NOT WORK, only works for the case of rows 
x2[0] # shorthand for x2[0, :]

#NumPy arrays support the concept of views, which are alternative array representations that share the same data buffer with the original array. These views do not create a new copy of the data but provide a different way to access and manipulate the underlying data.

#If we modify subarrays created from a view, the original data will change

In [55]: x2
Out[55]:
array([[1, 7, 7, 0],
       [0, 1, 0, 9],
       [6, 8, 4, 3]])

In [56]: x2_sub = x2[:2, :2]

In [57]: x2_sub
Out[57]:
array([[1, 7],
       [0, 1]])

In [58]: x2_sub[0, 0] = 0

In [59]: x2
Out[59]:
array([[0, 7, 7, 0],
       [0, 1, 0, 9],
       [6, 8, 4, 3]])


#On the other hand, copying an array in NumPy creates a new array object with its own separate data buffer. Any modifications made to the copied array do not affect the original array, and vice versa. 
x2_sub_copy = x2[:2, :2].copy()

#Reshaping of arrays 
In [69]: grid = np.arange(0, 10)

In [70]: grid
Out[70]: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]: grid = grid.reshape(2,5)

In [73]: grid
Out[73]:
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

(3, 4)