#### Array Creation
1. Create a 1D NumPy array with values [10, 20, 30, 40, 50].
2. Create a 2D array with the shape (3, 4) filled with the number 7.
3. Generate an array with a linear sequence from 5 to 25 with a step size of 5.
4. Create a 3x3 array of random floats between 0 and 1.

In [6]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [14]:
#Create a 1D NumPy array with values [10, 20, 30, 40, 50]
array = np.array([10, 20, 30, 40, 50])
print(array)

#Create a 2D array with the shape (3, 4) filled with the number 7.
array2D = np.full((3,4), 7)
print(array2D)

#Generate an array with a linear sequence from 5 to 25 with a step size of 5.
lineararray = np.linspace(5, 25, 5)
print(lineararray)

#Create a 3x3 array of random floats between 0 and 1.
arrayfloat = np.random.random((3,3))
print(arrayfloat)

[10 20 30 40 50]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[ 5. 10. 15. 20. 25.]
[[0.9305645  0.53186335 0.39198556]
 [0.6185229  0.8893854  0.28572376]
 [0.34473243 0.76039834 0.04961135]]


#### Attributes of Arrays
5. Define a 2D array with shape (2, 3). What are its `shape`, `ndim`, and `size` attributes?
6. If an array has `shape = (4, 5)` and each element occupies 8 bytes, calculate the total size in bytes.

In [ ]:
#### Attributes of Arrays

# Define a 2D array with shape (2, 3). What are its `shape`, `ndim`, and `size` attributes?
array2D = np.random.randint(0, 10, (2,3))
print('Shape: ', array2D.shape)
print('Dimensions: ', array2D.shape)
print('Size: ', array2D.size)

# If an array has `shape = (4, 5)` and each element occupies 8 bytes, calculate the total size in bytes.



Shape:  (2, 3)
Dimensions:  (2, 3)
Size:  6


To calculate the total size in bytes of a NumPy array, we use the following formula:

$$
\text{Total size in bytes} = \text{Number of elements} \times \text{Bytes per element}
$$

### Given:
- The shape of the array is `(4, 5)`, which means the array has 4 rows and 5 columns.
  - Number of elements in the array = \( 4 \times 5 = 20 \)
  
- Each element occupies 8 bytes.

### Calculation:

$$
\text{Total size in bytes} = 20 \times 8 = 160 \, \text{bytes}
$$

Thus, the total size of the array in bytes is **160 bytes**.

### Explanation:
- The shape `(4, 5)` indicates there are 4 rows and 5 columns, making 20 total elements.
- Since each element occupies 8 bytes, multiplying the total number of elements by 8 gives the total size in bytes.


#### Indexing and Slicing
7. Extract the first three elements from the array `[4, 8, 12, 16, 20]`.
8. From the 2D array `[[1, 2, 3], [4, 5, 6], [7, 8, 9]]`, extract the first two rows and the last column.
9. Reverse the array `[1, 2, 3, 4, 5]`.
10. Extract every second column from the array `[[10, 20, 30], [40, 50, 60], [70, 80, 90]]`.

In [27]:
#Extract the first three elements from the array `[4, 8, 12, 16, 20]`
array = [4, 8, 12, 16, 20]
#print(array[:3])

#From the 2D array `[[1, 2, 3], [4, 5, 6], [7, 8, 9]]`, extract the first two rows and the last column.
array2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
#print(array2D)
array2D_sorted = array2D[:2, -1]
#array2D_sorted = array2D[:-1]
print(array2D_sorted)

#Reverse the array `[1, 2, 3, 4, 5]`.
array = np.array([1, 2, 3, 4, 5])
array_reversed = array[::-1]
#print(array_reversed)

#Extract every second column from the array `[[10, 20, 30], [40, 50, 60], [70, 80, 90]]
array = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
array_second = array[::2]
print(array_second)

[3 6]
[[10 20 30]
 [70 80 90]]
